"""Compose review evidence from existing captures; never re-render or alter the site."""
from pathlib import Path
import hashlib, json, shutil, struct
from PIL import Image, ImageDraw, ImageFont

project = Path(__file__).resolve().parents[3]
evidence = project / "docs/evidence/g3cr7v2r4-preview-gift"
reference = Path("C:/Users/34707/AppData/Local/Temp/codex-clipboard-99766e2c-9a13-4fc1-af3d-26427d502667.png")
shutil.copyfile(reference, evidence / "owner-reference.png")
font = ImageFont.truetype("C:/Windows/Fonts/arial.ttf", 28)
small = ImageFont.truetype("C:/Windows/Fonts/arial.ttf", 24)
canvas = Image.new("RGB", (2200, 4500), "#f8f4f2")
draw = ImageDraw.Draw(canvas)
draw.text((36, 22), "Birthday Magazine — Owner reference / final candidate", font=font, fill="#29232a")
def cell(file, label, x, y, width, height):
    draw.text((x, y), label, font=small, fill="#713f5d")
    im = Image.open(evidence / file).convert("RGB")
    im.thumbnail((width, height - 44), Image.Resampling.LANCZOS)
    canvas.paste(im, (x + (width - im.width)//2, y + 42))
cell("owner-reference.png", "Owner reference (generated by Owner)", 36, 82, 1046, 810)
cell("confirm/preview-empty-1440.png", "Final / 1440 / no photo", 1118, 82, 1046, 810)
cell("before/preview-photo-1440.png", "Before / 1440 / browser-local photo", 36, 930, 1046, 820)
cell("confirm/preview-photo-2048.png", "Final / 2048 / browser-local photo", 1118, 930, 1046, 820)
cell("before/preview-photo-375.png", "Before / 375", 36, 1790, 480, 2550)
cell("confirm/preview-photo-375.png", "Final / 375", 556, 1790, 480, 2550)
cell("confirm/preview-no-js-1440.png", "Final / 1440 / no JavaScript", 1118, 1790, 1046, 1000)
cell("confirm/preview-empty-2048.png", "Final / 2048 / no photo", 1118, 2860, 1046, 1000)
draw.text((1118, 3990), "Static HTML/CSS magazines. No page flip.", font=small, fill="#29232a")
draw.text((1118, 4030), "Source/runtime hashes and network proofs:", font=small, fill="#29232a")
draw.text((1118, 4070), "runtime-boundary.json / delivery.json", font=small, fill="#29232a")
target = evidence / "final-contact-sheet.jpg"
canvas.save(target, quality=90, optimize=True)
items = []
for file in sorted(evidence.rglob("*")):
    if file.suffix.lower() not in {".png", ".jpg"}: continue
    with Image.open(file) as im: size = im.size
    data = file.read_bytes()
    items.append({"file": file.relative_to(evidence).as_posix(), "dimensions": list(size), "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(), "absolutePath": str(file)})
(evidence / "image-manifest.json").write_text(json.dumps(items, ensure_ascii=False, indent=2), encoding="utf-8")
font_bytes = (project / "poc/g3c/preview-plugin/assets/preview-gift-20261005/PlayfairDisplay.ttf").read_bytes()
font_version = set()
for i in range(struct.unpack_from(">H", font_bytes, 4)[0]):
    tag, _, offset, _ = struct.unpack_from(">4sIII", font_bytes, 12 + 16*i)
    if tag != b"name": continue
    _, count, strings = struct.unpack_from(">HHH", font_bytes, offset)
    for j in range(count):
        platform, _, _, name, length, start = struct.unpack_from(">HHHHHH", font_bytes, offset + 6 + 12*j)
        if name != 5: continue
        raw = font_bytes[offset + strings + start:offset + strings + start + length]
        font_version.add(raw.decode("utf-16-be" if platform in (0, 3) else "mac_roman"))
font_version = sorted(font_version)
assets = []
for file in sorted((project / "poc/g3c/preview-plugin/assets/preview-gift-20261005").iterdir()):
    data = file.read_bytes()
    assets.append({"file": file.name, "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()})
(evidence / "asset-manifest.json").write_text(json.dumps({"fontNameVersion": font_version, "assets": assets}, indent=2), encoding="utf-8")
print(json.dumps({"contactSheet": str(target), "bytes": target.stat().st_size, "images": len(items), "fontVersion": font_version}))
